### ISSUE TITLE
RStudio crash when partial have args with names identical to that in the original f()

### ISSUE THREAD

**Issue by BBrill** [hadley/pryr#14]
Hi, I'm a simple user of R, and not so experienced. After reading Advanced R programming I have started using partial() which I found very useful, however I found that when passing to partial() names identical to that in the original function RStudio crash.
I think to understand what happens, and obviously there is a simple solution (not using the same names!:)), however I will report here a reproducible example. 

``` r
#Run on windows7 x64 , R 3.0.2

library(pryr)
x <- runif(1e4)
y <- runif(1e4)
test <- function(x, y) mean(x+y)
test <- partial(test, x=x)
test(y=y)
```

Thank you for your book, clearly let me progress with R.

**Comment by rpln** [comment]
The final `test()` function that you have created calls itself, hence an infinite recursion. Better to name it something else, e.g. `test_fixed_x <- partial(test, x = x)`

Also, be careful if you change `x` later on; it will affect your function created from `partial()` as `x` is only evaluated when needed. You can force evaluation of the default arguments by using `.lazy = FALSE`: 
```
test_fixed_x <- partial(test, x=x, .lazy = FALSE)
```
