### ISSUE TITLE
pryr::object_size() may be skipping function arguments or promises

### ISSUE THREAD

**Issue by JohnMount** [hadley/pryr#37]
I believe pryr::object_size() is not seeing some environments associated with function arguments (probably missing environments associated with promises).  I have an example where the size reported by crude serialization is much larger than pryr::object_size().  

The issue is related to the discussion from http://www.win-vector.com/blog/2015/04/how-and-why-to-return-functions-in-r/ and an example is below.

```r
build1 <- function(z) {
  function() { print(z) }
}

build2 <- function(z) {
  force(z)
  function() { print(z) }
}

# try to print sizes of components
breakItDown = function(mod) {
  attr <- names(attributes(mode))
  if(is.function(mod)) {
     return(list(env=breakItDown(environment(mod)),
                 formals=breakItDown(formals(mod)),
                 body=breakItDown(body(mod)),
                 attr=attr))
  } 
  return(list(items=lapply(mod, FUN=function(x){length(serialize(x, NULL))}),
              attr=attr))
}


expmt <- function(touchEvertying=FALSE) {
  d <- data.frame(x=1:100000000)
  f1 <- build1(5)
  print(paste("pryr::object_size(f1)",pryr::object_size(f1)))
  print(paste('f1 serialize size',
           length(serialize(f1, NULL))))
  if(touchEvertying) {
    breakItDown(f1)
    print('zap f1')
  }
  print(paste("pryr::object_size(f1)",pryr::object_size(f1)))
  print(paste('f1 serialize size',
           length(serialize(f1, NULL))))
  f2 <- build2(5)
  print(paste("pryr::object_size(f2)",pryr::object_size(f2)))
  print(paste('f2 serialize size',
           length(serialize(f2, NULL))))
}

expmt(FALSE)
## [1] "pryr::object_size(f1) 33888"
## [1] "f1 serialize size 400029066"
## [1] "pryr::object_size(f1) 33888"
## [1] "f1 serialize size 400029070"
## [1] "pryr::object_size(f2) 33832"
## [1] "f2 serialize size 28388"

expmt(TRUE)
## [1] "pryr::object_size(f1) 33888"
## [1] "f1 serialize size 400029066"
## [1] "zap f1"
## [1] "pryr::object_size(f1) 33832"
## [1] "f1 serialize size 28388"
## [1] "pryr::object_size(f2) 33832"
## [1] "f2 serialize size 28388"
```

**Comment by hadley** [comment]
A simpler example looks ok to me:

```R
f <- function(x) {
  function() {
    force(x)
    2
  }
}

g <- function() {
  x <- 1:1e7
  f({message("evaled"); 10})
}

h <- g()
pryr::object_size(h)
#> 40 MB

h()
pryr::object_size(h)
#> 5.33 kB
```

**Comment by isomorphisms** [comment]
This may be on the same theme or it may need a different ticket but I'll report it here just to avoid potential duplication.

```
e <- new.env(hash=T, size=1e5)
e %>% object_size          #big
wee <- new.env(parent=e, size=10)
wee %>% object_size        #also big
wee %>% object.size         #small
```

**Comment by hadley** [comment]
@isomorphisms I don't understand what the problem is there - the results look ok to me. Can you please file a new issue?

**Comment by JohnMount** [comment]
So I thought my example showed a problem where there is something large in an object that length(serialize(,NULL)) sees and pryr::object_size() does not.  If I understand Hadley's April comment his simpler example does not see the problem ("looks ok" meaning doesn't see a problem).  So my question is (and very sorry for being a bother): is "closed" "closed fixed" or "closed don't see any problem"?

**Comment by hadley** [comment]
Closed = closed, I don't see any problem.  I don't think `serialize()` is necessarily trustworthy for estimating memory usage here.

**Comment by JohnMount** [comment]
I am liking my original example less and less (I no longer I think it is clear what is going on there).  But I guess I do have a question: should a function's size include the size of the environment needed to form its closure?  And should object size depend on the environment the size is estimated in.  Here is an example:

build1 <- function() {
  x <- 1:1e+7 # this variable will be in f's closure
  f = function() { FALSE }
  print(paste("serialize size in construciton environment",length(serialize(f, NULL))))
  print(paste("pryr::object_size in construction environment",pryr::object_size(f)))
  f
}

f1 <- build1()
## [1] "serialize size in construciton environment 40019891"
## [1] "pryr::object_size in construction environment 23864"
print(paste("serialize size in global",length(serialize(f1, NULL))))
## [1] "serialize size in global 40019891"
print(paste("pryr::object_size in global environment",pryr::object_size(f1)))
## [1] "pryr::object_size in global environment 40024184"
