### ISSUE TITLE
address() seems to give wrong answer when used inside a function on a function argument

### ISSUE THREAD

**Issue by paciorek** [hadley/pryr#67]
I see a difference between the address reported by `pryr::address` and by `.Internal(inspect())`:

```
library(pryr)
#> Registered S3 method overwritten by 'pryr':
#>   method      from
#>   print.bytes Rcpp
set.seed(1)
x <- rnorm(10)
f <- function(data){
    force(data) # not needed; same issue without this line
    print(.Internal(inspect(data)))
    print(address(data))
    return(NULL)
}

myFun <- f(x)
#> @55cbd3bcbcd8 14 REALSXP g0c5 [NAM(7)] (len=10, tl=0) -0.626454,0.183643,-0.835629,1.59528,0.329508,...
#>  [1] -0.6264538  0.1836433 -0.8356286  1.5952808  0.3295078 -0.8204684
#>  [7]  0.4874291  0.7383247  0.5757814 -0.3053884
#> [1] "0x55cbd3046108"
address(x)
#> [1] "0x55cbd3bcbcd8"
```

Here's my setup, but note I see the same issue on R 3.5.0 on a Mac.

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pryr_0.1.4           RhpcBLASctl_0.18-205 SCF_3.6.1           

loaded via a namespace (and not attached):
[1] compiler_3.6.1   magrittr_1.5     tools_3.6.1      Rcpp_1.0.2      
[5] stringi_1.4.3    codetools_0.2-15 stringr_1.4.0   
```

**Comment by lionel-** [comment]
`inspect()` gives you the address of the promise, `address()` gives you the address of the value of the promise.

Note that these functions are not meant for programming, just for discovery of internals.

**Comment by lionel-** [comment]
oops sorry I should have read the output.

It looks like this is the other way around: `address()` gives the address of the promise. You can see in its implementation that it uses `substitute()` to avoid forcing the object.

**Comment by paciorek** [comment]
Hmm, but the promise has already been evaluated by the time `address()` is called in the reprex so shouldn't `data` be the actual value at the point `address()` is called? It's not even clear to me how the promise itself would even still be available at the point `address()` is called.

**Comment by lionel-** [comment]
Internally a promise is not replaced by its value, its `PRVALUE` field is filled in with the value and the interpreter plucks it on subsequent evaluations.

**Comment by paciorek** [comment]
Ah, thanks, that's helpful.

Given that you might consider adding a note in the documentation of `address()` that points out that the result will differ from `.Internal(inspect())` when used on a function argument.
