### ISSUE TITLE
`pryr` is not available (for R version 3.0.2)

### ISSUE THREAD

**Issue by Mullefa** [hadley/pryr#7]
On running `install.packages('pryr')` I get the following warning: `package ‘pryr’ is not available (for R version 3.0.2)`. (OS: Red Hat Linux)

**Comment by hshallal** [comment]
Hi Mullefa, this may be too late of a question, but how could you install pryr just because it is available on CRAN? I downloaded the tar.gz file of the library but I have no clue how to install it on a new R version? Thanks
